 $('.example-crops .typeahead').typeahead({
              name: 'Crops',
          local: [ "Apple",
          "Banana",
          "Bhindi(Ladies Finger)",
          "Bitter gourd",
          "Bottle gourd",
          "Brinjal",
          "Cauliflower",
          "Chilly Capsicum",
          "Colacasia",
          "Cucumbar",
          "French Beans (Frasbean)",
          "Green Chilly",
          "Lemon",
          "Litchi",
          "Mango",
          "Methi",
          "Mousambi",
          "Onion",
          "Peas Wet",
          "Pomegranate",
          "Potato",
          "Pumpkin",
          "Raddish",
          "Spinach",
          "Tomato",
          "Paddy(Dhan)",
          "Bengal Grams(Gram)",
          "Corriander seed",
          "Maize",
          "Soyabean",
          "Wheat",
          "Cabbage",
          "Coriander",
          "Cock",
          "Fish",
          "Capsicum",
          "Tinda",
          "Other Vegetable",
          "Round gourd",
          "Toria",
          "Pointed gourd (Parval)",
          "Rice",
          "Ridgeguard",
          "Sweet Pumpkin",
          "Bajra(Pearl Millet)",
          "Barley (Jau)",
          "Mustard",
          "Ghee",
          "Green ginger",
          "Gur(Jaggery)",
          "Mustard Oil",
          "Sunflower",
          "Red Grams",
          "Jack Fruit",
          "Maida Atta",
          "Wheat Atta",
          "Arhar (Tur)",
          "Castor Seed",
          "Cummin Seed(Jeera)",
          "Groundnut",
          "Jowar(Sorgham)",
          "Cotton",
          "Ground Nut Seed",
          "Methi Seeds",
          "Sesamum(Sesame,Gingelly,Til)",
          "Banana - Green",
          "Cowpea(Veg)",
          "Drumstick",
          "Elephant Yam (Suran)",
          "Gwar",
          "Indian Beans (Seam)",
          "Kartali (Kantola)",
          "Little gourd (Kundru)",
          "Peas cod",
          "Pegeon Pea (Arhar Fali)",
          "Surat Beans (Papadi)",
          "Pears",
          "Water Melon",
          "Sponge gourd",
          "Mango (Raw-Ripe)",
          "Cluster beans",
          "Lime",
          "Amaranthus",
          "Amphophalus",
          "Ashgourd",
          "Beetroot",
          "Carrot",
          "Papaya (Raw)",
          "Snakeguard",
          "Tapioca",
          "Arecanut(Betelnut/Supari)",
          "Black pepper",
          "Copra",
          "Galgal(Lemon)",
          "Coconut",
          "Coffee",
          "Ginger",
          "Pepper garbled",
          "Rubber",
          "Jamun",
          "Papaya",
          "Field Pea",
          "Leafy Vegetable",
          "Plum",
          "Yam (Ratalu)",
          "Black Grams (Urd Beans)",
          "Sugar",
          "Gingelly (Sesamum, Sesame, Til) ",
          "Turmeric",
          "Chili Red",
          "Linseed",
          "Peas(Dry)",
          "Masur Dal", 
          "Tamarind Fruit",
          "Groundnut (Split)",
          "Sunflower Seed",
          "Groundnut pods (raw)",
          "Orange",
          "Cashewnuts",
          "Dry Chillies",
          "Green Peas",
          "Yam",
          "Garlic",
          "Bull",
          "Cow",
          "Goat",
          "He Baffalo",
          "She Baffalo",
          "Sheep",
          "Cowpea (Lobia)(Asparagus)",
          "Green Grams (Moong)",
          "Ajwan",
          "Tamarind Seed",
          "Jute",
          "Green Gram Dal",
          "Squash(Chappal Kadoo)",
          "Beans",
          "Beaten Rice",
          "Betal Leaves",
          "Lak",
          "Other Forest Product",
          "Other Pulses",
          "Other Spices",
          "Big Gram",
          "Isabgul (Psyllium)",
          "Chikoos(Sapota)",
          "Onion Green",
          "Soanf",
          "Suva (Dill Seed)",
          "Horses Gram",
          "Cucumber (Long Melon)",
          "Grapes",
          "Guava",
          "Peach",
          "Other Fruits",
          "Seetapal",
          "Pine Apple",
          "Mashrooms",
          "Dalda",
          "Soji",
          "Lentil(Masur)",
          "Moath Dal",
          "Alasande Gram",
          "Avare Dal",
          "Chennangidal",
          "Navane",
          "Ragi (Finger Millet)",
          "Alsandikai",
          "Bunch Beans",
          "Green Avare (W)",
          "Karbuja",
          "Knool Khol",
          "Seemebadnekai",
          "Sweet Lime",
          "Thondekai",
          "Neem Seed",
          "Tender Coconut",
          "Safflower",
          "Marygold(Calcutta)",
          "Rose(Loose)",
          "Sweet Potato",
          "Soapnut",
          "Suvarna Gadde",
          "Ox",
          "Coconut Oil",
          "Gingelly Oil",
          "Mint(Pudina)",
          "Pepper ungarbled",
          "Tea",
          "Duster Beans",
          "Kabuli Chana(Chickpeas-White)",
          "Hippe Seed",
          "Jasmine",
          "Kakada",
          "Mataki",
          "Bay leaf (Tejpatta)",
          "Broomstick",
          "Musk Melon",
          "She Goat",
          "Egg",
          "Taramira",
          "Wool",
          "Tobacco",
          "T.V. Cumbu",
          "Varagu",
          "Niger Seed (Ramtil)",
          "Turmeric (raw)",
          "Hen",
          "White Pumpkin",
          "Mahua",
          "Lotus Sticks",
          "Dry Grapes",
          "Same/Savi",
          "Citrus Fruit",
          "Coconut Seed",
          "Nutmeg",
          "Turnip",
          "Hybrid Cumbu",
          "Thinai (Italian Millet)",
          "Balekai",
          "Gram Raw(Chholia)",
          "Millets",
          "Other Tubers" ]
                  
               });
